#numbers
a=10
b=12
print(id(a))
print(a+b)
print(a%b)
#strings
str1="10000 coders"
print(str1[5])
print(str1[-4])
#list
a=[4,5,6,7,8,9]
print(type(a))
print(id(a))
print(len(a))
print(a[3])
a[3]=100
print(a)
#tuple
b=(1,2,3,4,5,6,7.2,"india")
print(id(b))
print(type(b))
print(len(b))
print(b[5])
#dict
c={"khaleja": "mahesh", "salar": "prabhas", "kingdom": "vijay", "devara": "ntr"}
print(len(c))
print(id(c))
print(c)
print(c["salar"])
#set
s={2,3,4,5,6,7,}
print(s)
print(len(s))
s.add(300)
print(s)
print(type(s))
#frosenset
f={2,3,4,5,6}
print(f)
